go.mod
manager/controllers/step_controller.go
runner/sidecar/sidecar.go

```
sources_errors{sourceName="default"} 0
sources_rate{sourceName="default"} 0.4
sources_total{sourceName="default"} 31
```

feat(runner): Emit Prometheus metrics

---

config/ci.yaml
config/dev.yaml
config/stan-dev/single-server-stan.yml

Fixes: https://github.com/argoproj-labs/argo-dataflow/issues/77

fix: expose stan monitoring port

---

config/ci.yaml
config/dev.yaml
config/stan-dev.yaml
examples/dataflow-stan-default-secret.yaml
test/stan.go
test/stress/stan_test.go
testapi/stan.go

`go test -v --tags test ./test/stress -run TestStan*`

test: stan stress

---

docs/EVENTS_INTEROP.md

docs: Use Argo Events sources

---

docs/EVENTS_INTEROP.md

docs: use Argo Events sources by watching messages in eventbus

---

runner/sidecar/sinks.go
runner/sidecar/sources.go
runner/sidecar/stan.go

feat: stan reliable auto reconnection

---

CHANGELOG.md
api/v1alpha1/stan.go
config/ci.yaml
config/crd/bases/dataflow.argoproj.io_pipelines.yaml
config/crd/bases/dataflow.argoproj.io_steps.yaml
config/default.yaml
config/dev.yaml
config/quick-start.yaml
examples/dataflow-stan-default-secret.yaml
runner/sidecar/sinks.go
runner/sidecar/sources.go
runner/sidecar/stan.go

feat: expose maxInflight for stan config

---

docs/STEPS.md

Removing unnecessary text in docs.

docs: Update STEPS.md

---

api/v1alpha1/container_builder.go
api/v1alpha1/container_supplier.go
api/v1alpha1/step_types.go
api/v1alpha1/step_types_test.go
examples/git/go.mod
examples/git/go.sum
runtimes/golang1-16/go.mod
runtimes/golang1-16/go.sum

feat: Drop-all capabilities by default. Fixes #175

---

runner/sidecar/sink/stan/stan.go
runner/sidecar/source/stan/stan.go

chore: add namespace to stan client id

---

Makefile
docs/EXAMPLES.md
examples/301-http-pipeline.py
examples/301-http-pipeline.yaml
examples/dataflow-103-http-main-source-default-secret.yaml
runner/sidecar/kafka.go
runner/sidecar/kafka_test.go
runner/sidecar/s3.go
runner/sidecar/shared/kafka/kafka.go
runner/sidecar/shared/stan/stan_conn.go
runner/sidecar/sidecar.go
runner/sidecar/sink/db/db.go
runner/sidecar/sink/http/http.go
runner/sidecar/sink/kafka/kafka.go
runner/sidecar/sink/s3/s3.go
runner/sidecar/sink/stan/stan.go
runner/sidecar/sinks.go
runner/sidecar/source/http/http.go
runner/sidecar/source/kafka/kafka.go
runner/sidecar/source/s3/s3.go
runner/sidecar/source/stan/stan.go
runner/sidecar/sources.go
runner/sidecar/stan.go
test/http.go
test/pipeline.go
test/stress/http_stress_test.go
test/stress/test-results.json
testapi/http.go

fix!: Add authentication to HTTP source. Fixes #152

---

Dockerfile
api/v1alpha1/step_types.go
api/v1alpha1/step_types_test.go
docs/EXAMPLES.md
manager/controllers/step_controller.go
runner/init/init.go
runner/sidecar/in.go
runner/sidecar/sidecar.go
runner/sidecar/source/s3/s3.go
test/http.go
test/service.go
test/stress/http_stress_test.go
test/stress/test-results.json
testapi/http.go

feat!: Change HTTP endpoints to have TLS v1.2. Fixes #178

---

runner/sidecar/sink/kafka/kafka.go
test/kafka-e2e/kafka_test.go

Signed-off-by: Vigith Maurice <vigith@gmail.com>
fixes #270

add kafka async metrics

---

api/v1alpha1/step_types.go
api/v1alpha1/step_types_test.go
config/ci.yaml
config/default.yaml
config/default/kustomization.yaml
config/default/lead-replica-priorityclass.yaml
config/dev.yaml
config/quick-start.yaml

feat: Use pod priority class to prioritize the lead replica. Fixes #269

---

runner/sidecar/sources.go
test/e2e/metrics_test.go

feat: export prometheus metrics from memory

---

manager/controllers/scaling/scaling.go
manager/controllers/scaling/scaling_test.go
manager/controllers/step_controller.go

fix: requeue interval change

---

manager/controllers/scaling/scaling.go

fix: more reasonable desired replicas calculation

---

runner/sidecar/source/kafka/handler.go

Signed-off-by: Alex Collins <alex_collins@intuit.com>

fix: Partial revert of 76e1d95

---

docs/STRESS.md

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

chore: Update Large TPS testing in stress doc

---

runner/sidecar/source/kafka/kafka.go

fix: lock assign/revoke partition code to prevent multiple consumers for same partition. Fixes #404

---

runner/sidecar/sink/jetstream/jetstream.go
runner/sidecar/source/jetstream/jetstream.go

fix: close jetstream connection

---

runner/sidecar/sink/kafka/kafka.go
runner/sidecar/sinks.go
test/http-fmea/http_fmea_test.go
test/kafka-e2e/kafka_test.go

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
closes #486

fix: Panic on two kafka sink

---

api/v1alpha1/git.go
config/ci.yaml
config/crd/bases/dataflow.argoproj.io_pipelines.yaml
config/crd/bases/dataflow.argoproj.io_steps.yaml
config/default.yaml
config/dev.yaml
config/quick-start.yaml
go.mod
runner/init/init.go

Fixes: #502
@alexec I wasn't able to build and test completely because of issues with M1 Mac. Would you please be able to build and see it it works as expected?

feat: add support for InsecureIgnoreHostKey

---

docs/CUSTOM_IMAGE.md

Signed-off-by: ab93 <avikbasu93@gmail.com>

docs: add python custom image example

---

docs/CLUSTER_QUICK_START.md

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

docs: Added cluster quick start document

---

docs/CUSTOM_IMAGE.md

Same as https://github.com/argoproj-labs/argo-dataflow/blob/main/Dockerfile#L14, also without it, next line with chmod doesn't work.

docs: Update CUSTOM_IMAGE.md

---

docs/DATAFLOW_VS_X.md

This commit corrects some grammar bugs (your vs you're) and makes the
comparison lists more consistent by starting each point with `if`.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

docs: correct grammar and improve consistency

---

sdks/nodejs/package-lock.json

https://github.com/argoproj-labs/argo-dataflow/security/dependabot/3

build(deps): upgrade ansi-regex

---

README.md

Signed-off-by: Edward Lee <edward_lee@intuit.com>

Added forwarding message to numaflow
